# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    env_file:
      - .env.docker
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/.venv  # Override the local .venv mount
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn 'app.main:app' --host=0.0.0.0 --port=8000 --reload
    networks:
      - bedrock-network  # Add this network
  
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:      # Change this line from 'expose:' to 'ports:'
      - "5432:5432"    # This maps container port 5432 to host port 5432
    env_file:
      - .env.docker
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bedrock-network  # Add this network

volumes:
  db-data:

# Define a custom network with a specific name
networks:
  bedrock-network:
    name: bedrock-network  # This explicit name makes it easier to reference

